In [1]:
# https://www.coursera.org/learn/vvedenie-mashinnoe-obuchenie/supplement/WQ8xO/rabota-s-viektorami-i-matritsami-v-numpy

In [2]:
import numpy as np

In [3]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))

In [10]:
X_mean = np.mean(X, axis=0)

In [11]:
X_dev = np.std(X, axis=0)

In [12]:
X_mean, X_dev

(array([1.04660715, 1.31352682, 0.74325525, 1.14313667, 0.91704301,
        0.45794819, 1.685127  , 0.89938808, 1.22091355, 0.70190035,
        0.7342082 , 1.04677186, 1.41476072, 1.01581206, 0.35436407,
        0.91179423, 1.32049206, 1.38205297, 0.85915563, 1.45201092,
        1.75265661, 1.12993466, 0.73334419, 0.98830685, 0.75257116,
        0.84141252, 1.01805951, 0.72172465, 1.19176884, 0.66206045,
        1.05644045, 0.87514207, 0.35417725, 1.39961473, 1.3462703 ,
        1.03891733, 0.98079437, 1.25687443, 1.53304372, 0.65943194,
        0.94751214, 1.45323481, 1.33221144, 1.12367846, 1.20543729,
        1.17573089, 0.38632897, 1.39213606, 0.99469702, 1.21123081]),
 array([10.42738759, 10.21735701,  9.98765512,  9.9835908 , 10.26002068,
        10.21991425,  9.84832584, 10.06450066,  9.97795734, 10.21339237,
         9.8214753 , 10.1553025 ,  9.66626218,  9.9217085 , 10.11959208,
        10.10763163, 10.07542189, 10.20321657, 10.04589383,  9.8830554 ,
         9.7516295 ,  9.95

In [14]:
np.mean(X - X_mean)

-3.126388037344441e-17

In [16]:
X_norm = (X - X_mean) / X_dev

In [19]:
np.nonzero(np.sum(X, axis=1) > 10)

(array([  0,   2,   5,   8,   9,  11,  13,  14,  15,  16,  18,  19,  20,
         22,  23,  25,  26,  28,  29,  30,  31,  32,  33,  34,  35,  36,
         37,  38,  41,  44,  45,  46,  47,  48,  49,  50,  51,  57,  58,
         59,  61,  63,  64,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         77,  79,  80,  81,  82,  83,  86,  87,  88,  91,  93,  94,  95,
         96,  97,  98,  99, 101, 102, 104, 105, 106, 107, 108, 109, 110,
        111, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
        125, 126, 127, 128, 129, 130, 133, 134, 135, 136, 137, 138, 139,
        140, 142, 143, 144, 147, 148, 149, 150, 151, 154, 155, 156, 157,
        159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 172,
        173, 175, 176, 177, 179, 180, 181, 182, 183, 185, 187, 188, 189,
        190, 192, 193, 194, 195, 196, 200, 201, 202, 203, 204, 205, 206,
        207, 208, 209, 210, 211, 212, 213, 215, 216, 217, 218, 220, 221,
        223, 225, 226, 227, 228, 229, 231, 234, 235

In [20]:
eye1, eye2 = np.eye(3), np.eye(3)

In [21]:
np.vstack((eye1, eye2))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])